services:
  api:
    build: .
    container_name: rag_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - milvus-standalone
      - opensearch
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]

  worker:
    build: .
    container_name: rag_worker
    env_file: .env
    depends_on:
      - redis
    command: ["python", "-m", "dramatiq", "app.jobs.worker", "--processes", "1", "--threads", "8"]

  redis:
    image: redis:8.2-alpine
    container_name: redis
    command: ["redis-server", "/etc/redis/redis.conf"] 
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      


  # --- Milvus standalone and deps ---
  etcd:
    image: quay.io/coreos/etcd:v3.5.18  # Updated from v3.5.5 to v3.5.18
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd-data:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "2379:2379"

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z  # Critical security update - specific version required
    container_name: milvus-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio-data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9001:9001"  # MinIO console
      - "9000:9000"  # MinIO API

  milvus-standalone:
    image: milvusdb/milvus:v2.6.0  # Updated from v2.4.8 to v2.6.0
    container_name: milvus-standalone
    depends_on:
      - etcd
      - minio
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - milvus-data:/var/lib/milvus
    command: ["milvus", "run", "standalone"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"   # gRPC
      - "9091:9091"     # HTTP/metrics/WebUI

  # --- OpenSearch for BM25 keyword search ---
  opensearch:
    image: opensearchproject/opensearch:2.13.0  # Can optionally update to 3.2.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true  # For dev only
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"  # Performance analyzer
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    name: rag-network

volumes:
  etcd-data:
  minio-data:
  milvus-data:
  opensearch-data:
  redis-data:
  azurite-data: